spyder-ide/spyder-unittest

- spyder_unittesting/widgets/unittestinggui.py
Some updates necessary to run plugin under Spyder 3 and Qt5. 
The add_pathlist_to_PYTHONPATH bit is similar to spyder-ide/spyder.line_profiler#9.
> add_pathlist_to_PYTHONPATH has moved to spyder.utils.misc

- spyder_unittesting/unittesting.py
- spyder_unittesting/widgets/tests/test_unittestinggui.py
- spyder_unittesting/widgets/unittestinggui.py
Only the directory name was actually used, so remove all references to the file name and the arguments from the running configuration. Fixes #8.
> Use only directory name to run tests

- .ciocheck
- spyder_unittest/unittest.py
- spyder_unittest/widgets/unittestgui.py
@jitseniesen I activated the autoformatters enforcement so now ciocheck HAS to be run before committing or pushing (`ciocheck spyder_unittest -dt` to avoid running tests all the time) otherwise if yapf makes a modification on the CI servers, it will fail :-)
Take a look at how the file was formatted, this is using the default yapf configuration. Looks good, no? we can now forget about how to format code and focus and what the code does.
@ccordoba12 thoughts :-)?
> PR: Update config and yapfy files

- spyder_unittest/backend/__init__.py
- spyder_unittest/backend/testrunner.py
- spyder_unittest/backend/tests/test_testrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This PR introduces a new class, `TestRunner`, which contains the backend code for running tests that used to be part of `UnitTestWidget`. This should make it easier to add support for other test frameworks. Uncoupling GUI and non-GUI parts of the code is probably also a cleaner design. Fixes #9.
> Split non-GUI code off from UnitTestWidget

- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/unittestgui.py
This is in preparation for the new API in Spyder 4; see spyder-ide/spyder#3727. Also fixes #16.
----
The widget does no longer call the Spyder application, but all communication goes via the plugin. 
If the user has not yet selected a working dir in which to run the unit tests, then suggest the project directory, or the cwd if no project is opened. Fixes #22.
> Use SpyderPluginWidget instead of SpyderPluginMixin

- setup.py
In the Debian autobuilders, the build fails with the following `UnicodeDecodeError` using Python 3.5:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)
```
Most likely, this is due to the copyright sign added as a result of the copyright header normalization.
The following patch fixes the problem.
> Fix parsing of module version

- setup.py
- spyder_unittest/backend/tests/__init__.py
- spyder_unittest/widgets/tests/__init__.py
Follow-up from #66. It would actually simplify the CI setup on Debian to have the tests installed with the module. This way, testing the packaged module for each supported Python version is just one `$py -m pytest --pyargs spyder_unittest` away, instead of having to manually extract the test suite.
> Install the tests alongside the module

- spyder_unittest/backend/frameworkregistry.py
- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_frameworkregistry.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/tests/test_configdialog.py
- spyder_unittest/widgets/unittestgui.py
The idea is that every testing framework has a class associated with it for running the tests and parsing the results. The framework registry keeps track of the supported testing frameworks, and creates the runners. This allows for easier extension to other testing frameworks (like unittest), possibly using additional plugins in the future. Fixes #41.
> Add framework registry for associating testing frameworks with runners

- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This implements support for running tests using the unittest package in the standard Python library. Fixes #4.
The parsing of the unittest output is not very robust and easily confused by print statements in the tests. I am opening a separate issue for this.
> Support unittest

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
Instead of displaying the full name for the tests in the widget (e.g. `spyder_unittest.backend.tests.test_frameworkregistry.test_frameworkregistry_when_empty`), which takes up quite a lot of space, display only the last part (`test_frameworkregistry_when_empty`). The user can hover over the name and the full name will appear in a tooltip. Fixes #11.
> Shorten test name displayed in widget

- circle.yml
> Install Spyder from github 3.x branch when testing on Circle

- conda.recipe/meta.yaml
- setup.py
- spyder_unittest/backend/frameworkregistry.py
- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_frameworkregistry.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/tests/test_configdialog.py
- spyder_unittest/widgets/unittestgui.py
This PR checks whether all the testing frameworks (nose, py.test, unittest) are installed. If not, then this is indicated when the user is asks to select a testing framework, and the user is prevented from selecting frameworks that are not available. Fixes #15 .
The PR also runs the tests by calling the Python interpreter directly (e.g., for py.test, it runs `python -m pytest` instead of the `py.test` executable), thus partially addressing #65 . It drops the dependencies on nose and py.test, because the plugin can now be used without either of them installed: it can still use unittest which is part of the standard library.
> Properly handle test frameworks which are not installed

- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
The configuration is saved in the project preferences (because it is probably specific to a particular project), so that the user does not have to specify the testing framework again in subsequent sessions. If no project is opened, the configuration is not saved. Fixes #43.
> Load and save configuration for tests

- spyder_unittest/tests/test_unittestplugin.py
- spyder_unittest/unittestplugin.py
Add unit tests for `UnitTestPlugin` (so the integration with Spyder proper is not tested). Thanks for @rlaverde for giving me an example of how to do this at spyder-ide/spyder-reports#15 .
Fixes #89 .
> Add unit tests for plugin

- spyder_unittest/backend/abbreviator.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/tests/test_abbreviator.py
- spyder_unittest/backend/tests/test_jsonstream.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
This is a further iteration of PR #75 which hides the module name when displaying test names in the plugin. As suggested there, this PR abbreviates the module name.
After:
As the tooltip shows, the test name `s.b.t.test_a.test_abbreviator_with_second_word_prefix_of_first` stands for `spyder_test.backends.tests.test_abbreviator.test_abbreviator_with_second_word_prefix_of_first` .
Before:
> Abbreviate module names when displaying test names

- spyder_unittest/backend/abbreviator.py
- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_abbreviator.py
- spyder_unittest/backend/tests/test_noserunner.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_pytestworker.py
- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This PR implements the proper handling of errors encountered by py.test while it collects the tests, for example syntax errors in a test file.
A complication is that these errors are reported (and should be displayed by) with the module name, but not with the test name. This is resolved by a change in design: instead of `TestDetails`, which contains both module and test name, every line in the test results table is associated with just a `str`.
Fixes #93.
> Handle errors encountered when py.test collect tests

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_pytestworker.py
- spyder_unittest/tests/test_unittestplugin.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This PR implements a way for the user to go to the definition of a test. Specifically, we record the location of the tests as recorded by py.test (this feature is not yet implemented for unittest and nose). When the user double clicks on a test, the editor will go the test definition. When the uer right-clicks, a context menu appears with two items: "expand" for expanding the test results in the tree and "go to definition" for going to the test definition. If the test is already expanses, then "expand" is replaced by "collapse". This context menu will help with #88.
Fixes #12.
> Implement go to test definition for py.test

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_pytestworker.py
This is more robust, because nodeid's are also used when processing the test reports. In particular, this fixes a bug which prevented the plugin to work correctly with test functions which are defined within a class.
Fixes #98 .
> Use nodeid when collecting tests using py.test

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
Make the header clickable so that the user can click there to sort on that column. I envisage the main use is to quickly find failing tests if there are many tests: sort by status and failing tests are sorted to top.
Fixes #94 .
> Allow user to sort tests

- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
The plugin reports the times taken for each test. This PR displays the times rounded to the nearest 0.01 ms (instead of the ridiculous precision reported now) and aligns the numbers to the right (so that the decimal points are aligned). Do not display any times If the unittest framework is used, because it does not report the time.
Fixes #86. Fixes #87.
> Improve display of test times

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/widgets/unittestgui.py
Relabel "Kill" button for stopping a test run to "Stop", for consistency with the rest of Spyder (in particular, the IPython console).
Fixes #92.
> Relabel 'Kill' button

- spyder_unittest/widgets/datatree.py
This uses the same red which used in Spyder's find/replace widget for regexp errors.
Fixes #96.
> Use paler shade of red as background for failing tests

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/tests/test_pytestrunner.py
Before, only the path relative to the root directory of the tests were stored. As a consequence, the "go to" command only works if Spyder's working directory is the same as the root directory of the tests.
Fixes #103.
> Store full path to file containing test in TestResult

- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
> Emit modelReset after sorting test results

- AUTHORS
- README.md
- setup.py
Update long description used on the Pypi website. Update README by adopting a more positive tone in funding announcement, moving it below the screen shot, and removing the headings with the badges (shamelessly lifted from spyder-ide/spyder#6923).
> Update Pypi description and README

- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/tests/test_pytestworker.py
This correctly handles errors that occur in pytest's collection phase.
Fixes #113
> Use str() to convert pytest's longrepr to a string

- .travis.yml
- README.md
- appveyor.yml
- circle.yml
- setup.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/tests/test_unittestplugin.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
The pytest testing framework uses the spelling "pytest" instead of "py.test" since at least version 3.0 released in August 2016. This PR propagates the change to the spyder plugin.
As a result, all existing testing configurations are rendered invalid. I decided to handle this by forcing users to select the framework again. I could have special-cased this when reading the config, but I think it's only a minor inconvenience for our users and the plugin is still in 0.x version.
> Replace 'py.test' by 'pytest'

- spyder_unittest/backend/noserunner.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/unittestgui.py
This fixes a code style warning which suddenly popped up on one of the CI servers.
> Remove unused variables when initializing localization

- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/tests/test_pytestworker.py
This is simpler and more robust. In fact, I have no idea why I did not do this originally.
Fixes #128
> PR: Use nodeid provided by pytest in itemcollected hook

- spyder_unittest/widgets/unittestgui.py
spyder-ide/spyder@e4c5b1a678b1e90be7191fa5c6f77acfb7aba8ca introduced dynamic window sizing and hence removed the size argument in the TextEditor constructor, which results in an error here. This commit restores the previous behavior.
The dynamic sizing doesn't work for me: if I don't explicitly resize the window I end up with a window size of 278 x 242 pixel on my 1900 x 1200 double screen setup (Windows 10). If I just specify `te.show()` instead of `te.resize(700, 500)` then I get the same 700 x 500 window size. Maybe someone more knowledgeable about QT can get the dynamic sizing to work, but for the time being this PR just restores the old behavior.
> Fix TextEditor constructor

- spyder_unittest/widgets/unittestgui.py
using `BaseDialog`'s `set_dynamic_width_and_height`.
This is further to #139 and resolves spyder-ide/spyder#12202.
> Dynamic sizing of text editor window

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
- Fix status_label if no results to show
status_label update is triggered by assignment of test results in
process_finished. In case of no results, process_finished is called
with an empty list of testresults. This empty list must also be
assigned in order to trigger the status_label update, otherwise the
status remains "Running tests ..." after finishing. So we have to
differentiate between None and [] in the if clause.
Without the fix it looks like this after running when no tests were discovered:
- Reset status_label when running tests is stopped
and make parsing errors in unittestrunner.load_data indeed ignored silently
(it relies on the condition that the result includes the final line of all
dashes, otherwise an Indexerror will occur)
Without the fix the status label "Running tests …
> Fix status label

- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_noserunner.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
The corresponding menu item is called `Dependencies` and not `Show versions` to be consistent with spyder itself (it uses the same icon).
See also #115.
> Show version info of test installed frameworks and their plugins

- spyder_unittest/backend/abbreviator.py
- spyder_unittest/backend/tests/test_abbreviator.py
The name of a test is the dotted test function name possibly followed
by a list of parameters in brackets. These parameters can contain dots
as for example in [`test_unittestwidget_process_finished_updates_status_label`](https://github.com/spyder-ide/spyder-unittest/blob/57363140274af14151ae5826c77e47fdfa3df6ac/spyder_unittest/widgets/tests/test_unittestgui.py#L155)
from `test_unittestgui.py` where the label of the second parameter ends
with a dot, which led to the wrong abbreviation `'s.w.t.test_u.t.]'`. This
is fixed by not taking into account the parameter list when abbreviating.
Current:
Fixed:
> Fix abbreviator if name has parameters with dots

- spyder_unittest/widgets/unittestgui.py
instead of setting the label directly. Thus the data (text) is decoupled from the formatting (bold tags).
This also ensure the correct closing tag (`</b>` instead of `<b>)` is used, although the incorrect one also worked fine.
Just an insignificant change but  I think it makes the translation strings more consistent.
> Use set_status_label function

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_pytestworker.py
Pytest test filenames are relative to the `rootdir`. This `rootdir` is not
necessarily the directory from which discovery starts, i.e. `wdir` from
spyder-unittest's `config`. For details on how pytest determins the `rootdir` see
[Initialization: determining rootdir and inifile](https://docs.pytest.org/en/latest/customize.html#initialization-determining-rootdir-and-inifile.)
Filenames used to be resolved against `wdir`. If `wdir` is not the `rootdir` (as
described in the above link) this resulted in invalid resolved filenames.
This commit gets the `rootdir` in the `pytest_report_header` hook which is
called after all configuration is done and before any test collection
starts. This `rootdir` is then used for filename path resolution.
This resolves #145
> Fix pytest test filename path resolution

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/widgets/unittestgui.py
by patching `add_pathlist_to_PYTHONPATH`. This function first checks whether `PYTHONPATH` is set in the **actual** (!) OS environment and then changes the passed-in `env` list by either setting or prepending the `pathlist` to `PYTHONPATH`. The test failed if the OS environment in that the test is run hasn't set `PYTHONPATH`, as in the test, we call `add_pathlist_to_PYTHONPATH` with an `env` list where `PYTHONPATH` is already set.  
I'm not sure if this isn't a logic flaw in [`add_pathlist_to_PYTHONPATH`](https://github.com/spyder-ide/spyder/blob/e2db403d7a4a97690114f20da78e144ece3eeca6/spyder/utils/misc.py#L226): I think if `ipyconsole` is `False` it should look for `PYTHONPATH` not in the actual OS environment but in the passed-in `env` list. This doesn't play any role in the production …
> Fix test_pytestrunner_start

- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/tests/test_pytestrunner.py
Just some small code maintenance:
1. remove unused code:
The `'finished'` event is processed nowhere. Process output is obtained by `read_all_process_output` instead.
2. add unit test for `pytestrunner_finished`:
This function was only tested in the integration test. I forgot to add a unit test when changing this function in 35469b5dec6.
> Fix pytest output processing

- setup.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/unittestgui.py
In particular, this drops support for Python 2.
This is only a minimal PR. Another PR targetting a major release of the plugin will remove all Python 2 specific code.
Fixes #154.
> PR: Require Python 3.5 or later

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- requirements/conda.txt
- setup.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/tests/test_unittestplugin.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
I tested by hand that the main functionality works, though I did not test everything. All automatic tests internal to the plugin pass, but I disabled the tests that check the interaction with other plugins because it seems quite hard to port them.
Fixes #163
> PR: Update to Spyder 5.2 API

- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/locale/de/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/es/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/fr/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/hr/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/hu/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/ja/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/pl/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/pt_BR/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/ru/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/locale/spyder_unittest.pot
- spyder_unittest/locale/zh_CN/LC_MESSAGES/spyder_unittest.po
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_configdialog.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
Adds some minimal coverage reporting to the verbose output. Currently tested with pytest, and I think it'll work with nose. I don't know how to do this for unittest itself.
It's optional, a checkbox in the config dialog box.
Fixes #33
> PR: Add code coverage report

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_pytestworker.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/backend/zmqstream.py
- spyder_unittest/tests/test_unittestplugin.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/configdialog.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
> PR: Remove Python 2 compatibility code

- spyder_unittest/backend/noserunner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/pytestworker.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This PR checks the exit status of the pytest process and displays a message if it indicates an abnormal exit. This happens when pytest is run with the `--cov` flag to gather coverage information and pytest-cov is not installed.
Fixes #176
> PR: Display message if pytest exits abnormally

- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
In Python 3.11, the format of `unittest`'s output has changed.  Whereas in Python 3.10 and earlier, the output looks like this (the tests are taken from the test suite in this package):
```
test_fail (testing.test_unittest.MyTest) ... FAIL
test_ok (testing.test_unittest.MyTest) ... ok
======================================================================
FAIL: test_fail (testing.test_unittest.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "<<DIRECTORY>>/testing/test_unittest.py", line 4, in test_fail
def test_fail(self): self.assertEqual(1+1, 3)
AssertionError: 2 != 3
----------------------------------------------------------------------
Ran 2 tests in 0.000s
FAILED (failures=1)
```
in Python 3.11 (and presumably …
> Support changes to `unittest` in Python 3.11

- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
This is a follow-up to #190 as discussed there; this makes `spyder_unittest` use the version number of the requested Python interpreter rather than the system version.
> Use requested interpreter version when analysing unittest results

- .github/workflows/run-tests.yml
- requirements/tests.txt
- spyder_unittest/tests/conftest.py
Do not install deprecated codecov package and use Codecov GitHub Action instead to upload coverage reports.
Adapted from spyder-ide/spyder#20817.
> PR: Update codecov coverage upload to use GitHub Action

- .github/workflows/run-tests.yml
- requirements/conda.txt
- setup.py
- spyder_unittest/tests/conftest.py
- spyder_unittest/tests/test_unittestplugin.py
Make plugin compatible with Spyder 5.4.1 and later while keeping compatibility with Spyder 6 as currently in development. In fact, the plugin code already worked with Spyder 5.4.1 so the only changes are in the tests and in lowering the requirements.
Fixes #206
> PR: Allow plugin to be run with Spyder 5

- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/confpage.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_confpage.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
Currently, test names in the "Unit testing" pane are abbreviated, so for instance "spyder_unittest.backend.tests.test_abbreviator.test_abbreviator_with_one_word" is shown as "s.b.t.test_a.test_abbreviator_with_one_word". 
This PR adds a config option to control whether test names are abbreviated. The default is not to abbreviate (contrary to the current situation), because several users complained and nobody said that they like it.
Screenshot of new Preferences pane for the plugin:
Fixes #122.
> PR: Add config option to abbreviate test names

- .github/workflows/run-tests.yml
- spyder_unittest/backend/abbreviator.py
- spyder_unittest/backend/frameworkregistry.py
- spyder_unittest/backend/nose2runner.py
- spyder_unittest/backend/pytestrunner.py
- spyder_unittest/backend/runnerbase.py
- spyder_unittest/backend/tests/test_pytestrunner.py
- spyder_unittest/backend/tests/test_runnerbase.py
- spyder_unittest/backend/tests/test_unittestrunner.py
- spyder_unittest/backend/unittestrunner.py
- spyder_unittest/backend/workers/tests/test_pytestworker.py
- spyder_unittest/backend/workers/tests/test_unittestworker.py
- spyder_unittest/backend/workers/unittestworker.py
- spyder_unittest/backend/zmqreader.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_datatree.py
- spyder_unittest/widgets/tests/test_unittestgui.py
- spyder_unittest/widgets/unittestgui.py
This PR adds the menu item "Run only this test" to the context menu that appears when right-clicking on a test result. Selecting this menu item re-runs the associated test only, ignoring all the other tests.
Fixes #88
> PR: Add option to run a single test

- .github/workflows/run-tests.yml
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/confpage.py
- spyder_unittest/widgets/tests/test_confpage.py
Follow updates in Spyder API from PRs spyder-ide/spyder#20926, spyder-ide/spyder#21101 and spyder-ide/spyder#21233. Also, replace Python 3.8 by Python 3.11 in GitHub automatic test.
Fixes #215.
> Update plugin and tests for Spyder 6.0.0a2 and 6.0.0a3

- spyder_unittest/unittestplugin.py
Turns out it was easier than I initially thought. Just four lines worth of changes in `unittestplugin.py` to make sure these args are saved and loaded from the project config file.
Fixes #216.
> Add functionality to save and load command-line args

- .github/scripts/generate-without-spyder.py
- .github/workflows/run-tests.yml
- spyder_unittest/tests/conftest.py
- spyder_unittest/unittestplugin.py
- spyder_unittest/widgets/datatree.py
- spyder_unittest/widgets/tests/test_confpage.py
A couple of changes to the API, but mostly changes to ensure that the tests run.
Part of #221, but there is probably more to come.
> PR: Compatibility fixes for Spyder 6.0.0 alpha 5
